# Generated by Django 4.2.7 on 2025-10-22 14:27

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissioncoefficient",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", django.utils.translation.gettext_lazy("生产部")),
                    ("rd", django.utils.translation.gettext_lazy("研发部")),
                    ("administration", django.utils.translation.gettext_lazy("行政部")),
                    ("logistics", django.utils.translation.gettext_lazy("后勤部")),
                ],
                max_length=50,
                null=True,
                verbose_name=django.utils.translation.gettext_lazy("部门名称"),
            ),
        ),
    ]
