# Generated by Django 4.2.7 on 2025-10-22 14:35

from django.db import migrations, models
import django.utils.translation


def set_default_department(apps, schema_editor):
    """Set default department for existing records and migrate old values"""
    EmissionCoefficient = apps.get_model('coefficients', 'EmissionCoefficient')
    
    # Migrate old Chinese values to new English keys
    EmissionCoefficient.objects.filter(department='生产部').update(department='production')
    EmissionCoefficient.objects.filter(department='研发部').update(department='rd')
    EmissionCoefficient.objects.filter(department='行政部').update(department='administration')
    EmissionCoefficient.objects.filter(department='后勤部').update(department='logistics')
    
    # Set default for NULL values
    EmissionCoefficient.objects.filter(department__isnull=True).update(department='production')


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0002_emissioncoefficient_department"),
    ]

    operations = [
        # First, set default value for existing NULL records
        migrations.RunPython(set_default_department, reverse_code=migrations.RunPython.noop),
        
        # Then, alter the field to be non-nullable
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="department",
            field=models.CharField(
                choices=[
                    ("production", django.utils.translation.gettext_lazy("生产部")),
                    ("rd", django.utils.translation.gettext_lazy("研发部")),
                    ("administration", django.utils.translation.gettext_lazy("行政部")),
                    ("logistics", django.utils.translation.gettext_lazy("后勤部")),
                ],
                max_length=50,
                verbose_name=django.utils.translation.gettext_lazy("部门名称"),
            ),
        ),
    ]
