# Generated by Django 4.2.7 on 2025-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0003_alter_emissioncoefficient_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="unit",
            field=models.CharField(
                choices=[("KG", "KG"), ("L", "L")], max_length=20, verbose_name="单位"
            ),
        ),
    ]
