# Generated by Django 4.2.7 on 2025-10-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0004_alter_emissioncoefficient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="product_code",
            field=models.CharField(db_index=True, max_length=50, verbose_name="产品编号"),
        ),
    ]
