# Generated by Django 4.2.7 on 2025-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0005_alter_emissioncoefficient_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="product_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="产品名称"),
        ),
    ]
