# Generated by Django 4.2.7 on 2025-11-07 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0006_alter_emissioncoefficient_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissioncoefficient",
            name="product_code",
        ),
    ]
