# Generated by Django 4.2.7 on 2025-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0007_remove_emissioncoefficient_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="产品名称"
            ),
        ),
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="product_name_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="产品名称(英文)"
            ),
        ),
    ]
