# Generated by Django 4.2.7 on 2025-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0008_alter_emissioncoefficient_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="产品名称"
            ),
        ),
    ]
