# Generated by Django 4.2.7 on 2025-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0009_alter_emissioncoefficient_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncoefficient",
            name="coefficient",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="碳排放系数"
            ),
        ),
    ]
