# Generated by Django 4.2.7 on 2026-05-25 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0011_alter_emissioncoefficient_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissioncoefficient",
            name="department",
        ),
    ]
