# Generated by Django 4.2.7 on 2026-05-26 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coefficients", "0012_alter_department_blank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissioncoefficient",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="emissioncoefficient",
            name="product_name_en",
        ),
    ]
