# Generated by Django 4.2.7 on 2025-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200, verbose_name="酒店名称")),
                ("department", models.CharField(max_length=50, verbose_name="部门")),
                (
                    "product_code",
                    models.CharField(db_index=True, max_length=50, verbose_name="产品代码"),
                ),
                ("product_name", models.CharField(max_length=200, verbose_name="产品名称")),
                (
                    "category_level1",
                    models.CharField(max_length=100, verbose_name="一级分类"),
                ),
                (
                    "category_level2",
                    models.CharField(max_length=100, verbose_name="二级分类"),
                ),
                ("product_unit", models.CharField(max_length=20, verbose_name="产品单位")),
                (
                    "emission_coefficient",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="碳排放系数"
                    ),
                ),
                ("consumption_date_start", models.DateField(verbose_name="消耗开始日期")),
                ("consumption_date_end", models.DateField(verbose_name="消耗结束日期")),
                ("consumption_time_start", models.TimeField(verbose_name="消耗开始时间")),
                ("consumption_time_end", models.TimeField(verbose_name="消耗结束时间")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="消耗数量"
                    ),
                ),
                (
                    "carbon_emission",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="碳排放量(kgCO2e)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "物料消耗记录",
                "verbose_name_plural": "物料消耗记录",
                "ordering": ["-consumption_date_start", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel_name", "department"],
                        name="data_entry__hotel_n_482c35_idx",
                    ),
                    models.Index(
                        fields=["consumption_date_start", "consumption_date_end"],
                        name="data_entry__consump_ee0e9e_idx",
                    ),
                ],
            },
        ),
    ]
