# Generated by Django 4.2.7 on 2025-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialconsumption",
            name="hotel_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="酒店名称"),
        ),
    ]
