# Generated by Django 4.2.7 on 2025-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0003_alter_materialconsumption_category_level1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialconsumption",
            options={
                "ordering": ["-consumption_datetime", "-created_at"],
                "verbose_name": "物料消耗记录",
                "verbose_name_plural": "物料消耗记录",
            },
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_ee0e9e_idx",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_date_end",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_date_start",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_time_end",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_time_start",
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="consumption_datetime",
            field=models.DateTimeField(null=True, verbose_name="消耗日期时间"),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["consumption_datetime"], name="data_entry__consump_a0f416_idx"
            ),
        ),
    ]
