# Generated by Django 4.2.7 on 2025-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0004_alter_materialconsumption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialconsumption",
            name="special_note",
            field=models.TextField(blank=True, verbose_name="特殊备注"),
        ),
    ]
