# Generated by Django 4.2.7 on 2025-11-07 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0005_materialconsumption_special_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialconsumption",
            name="notes",
        ),
    ]
