# Generated by Django 4.2.7 on 2025-11-07 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0006_remove_materialconsumption_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialconsumption",
            name="product_code",
        ),
    ]
