# Generated by Django 4.2.7 on 2025-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0007_remove_materialconsumption_product_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialconsumption",
            options={
                "ordering": ["-consumption_date", "-consumption_time", "-created_at"],
                "verbose_name": "物料消耗记录",
                "verbose_name_plural": "物料消耗记录",
            },
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_a0f416_idx",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_datetime",
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="consumption_date",
            field=models.DateField(null=True, verbose_name="消耗日期"),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="consumption_time",
            field=models.TimeField(null=True, verbose_name="消耗时间"),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["consumption_date", "consumption_time"],
                name="data_entry__consump_80711f_idx",
            ),
        ),
    ]
