# Generated by Django 4.2.7 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0008_alter_materialconsumption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialconsumption",
            name="carbon_emission",
            field=models.DecimalField(
                decimal_places=6,
                editable=False,
                max_digits=12,
                verbose_name="碳排放量(kgCO2e)",
            ),
        ),
        migrations.AlterField(
            model_name="materialconsumption",
            name="emission_coefficient",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="碳排放系数"
            ),
        ),
        migrations.AlterField(
            model_name="materialconsumption",
            name="quantity",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="消耗数量"
            ),
        ),
    ]
