# Generated by Django 4.2.7 on 2025-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0009_alter_materialconsumption_carbon_emission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialconsumption",
            name="department",
            field=models.CharField(
                choices=[
                    ("production", "生产部"),
                    ("rd", "研发部"),
                    ("administration", "行政部"),
                    ("logistics", "后勤部"),
                    ("F&B", "F&B"),
                ],
                max_length=50,
                verbose_name="部门名称",
            ),
        ),
    ]
