# Generated by Django 4.2.7 on 2025-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0010_alter_materialconsumption_department"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["consumption_date", "category_level1"],
                name="data_entry__consump_3de0a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["consumption_date", "category_level2"],
                name="data_entry__consump_2bb384_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["consumption_date", "department"],
                name="data_entry__consump_10b3bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["category_level1", "category_level2"],
                name="data_entry__categor_265977_idx",
            ),
        ),
    ]
