# Generated by Django 4.2.7 on 2025-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0011_add_dashboard_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(blank=True, max_length=200, verbose_name="酒店名称"),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("production", "生产部"),
                            ("rd", "研发部"),
                            ("administration", "行政部"),
                            ("logistics", "后勤部"),
                            ("F&B", "F&B"),
                        ],
                        max_length=50,
                        verbose_name="部门名称",
                    ),
                ),
                ("consumption_date", models.DateField(verbose_name="消耗日期")),
                (
                    "consumer_count",
                    models.IntegerField(default=0, verbose_name="消费者人数"),
                ),
                (
                    "daily_carbon_emission",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="当日碳排总量(kgCO2e)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "消费者数据",
                "verbose_name_plural": "消费者数据",
                "ordering": ["-consumption_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel_name", "department"],
                        name="data_entry__hotel_n_634aa8_idx",
                    ),
                    models.Index(
                        fields=["consumption_date"],
                        name="data_entry__consump_fce7e3_idx",
                    ),
                ],
                "unique_together": {("hotel_name", "department", "consumption_date")},
            },
        ),
    ]
