# Generated by Django 4.2.7 on 2026-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0012_consumerdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumerdata",
            options={
                "ordering": ["-order_date", "-created_at"],
                "verbose_name": "消费者数据",
                "verbose_name_plural": "消费者数据",
            },
        ),
        migrations.AlterModelOptions(
            name="materialconsumption",
            options={
                "ordering": ["-order_date", "-created_at"],
                "verbose_name": "物料消耗记录",
                "verbose_name_plural": "物料消耗记录",
            },
        ),
        migrations.RemoveIndex(
            model_name="consumerdata",
            name="data_entry__hotel_n_634aa8_idx",
        ),
        migrations.RemoveIndex(
            model_name="consumerdata",
            name="data_entry__consump_fce7e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__hotel_n_482c35_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_80711f_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_3de0a9_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_2bb384_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialconsumption",
            name="data_entry__consump_10b3bf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="consumerdata",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_date",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="consumption_time",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="department",
        ),
        migrations.RemoveField(
            model_name="materialconsumption",
            name="hotel_name",
        ),
        migrations.AddField(
            model_name="consumerdata",
            name="order_date",
            field=models.DateField(null=True, verbose_name="订单日期"),
        ),
        migrations.AddField(
            model_name="consumerdata",
            name="restaurant",
            field=models.CharField(
                choices=[
                    ("production", "生产部"),
                    ("rd", "研发部"),
                    ("administration", "行政部"),
                    ("logistics", "后勤部"),
                    ("F&B", "F&B"),
                ],
                default="",
                max_length=50,
                verbose_name="餐厅",
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="order_date",
            field=models.DateField(null=True, verbose_name="订单日期"),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="restaurant",
            field=models.CharField(
                choices=[
                    ("production", "生产部"),
                    ("rd", "研发部"),
                    ("administration", "行政部"),
                    ("logistics", "后勤部"),
                    ("F&B", "F&B"),
                ],
                default="",
                max_length=50,
                verbose_name="餐厅",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consumerdata",
            unique_together={("restaurant", "order_date")},
        ),
        migrations.AddIndex(
            model_name="consumerdata",
            index=models.Index(
                fields=["restaurant"], name="data_entry__restaur_705725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerdata",
            index=models.Index(
                fields=["order_date"], name="data_entry__order_d_690cbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["restaurant"], name="data_entry__restaur_34417a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["order_date"], name="data_entry__order_d_17abf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["order_date", "category_level1"],
                name="data_entry__order_d_a13fd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["order_date", "category_level2"],
                name="data_entry__order_d_79144a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["order_date", "restaurant"],
                name="data_entry__order_d_f84981_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="consumerdata",
            name="consumption_date",
        ),
        migrations.RemoveField(
            model_name="consumerdata",
            name="department",
        ),
        migrations.RemoveField(
            model_name="consumerdata",
            name="hotel_name",
        ),
    ]
