# Generated by Django 4.2.7 on 2026-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0013_alter_consumerdata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialconsumption",
            options={
                "ordering": ["-order_date", "-consumption_time", "-created_at"],
                "verbose_name": "物料消耗记录",
                "verbose_name_plural": "物料消耗记录",
            },
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="consumption_time",
            field=models.TimeField(blank=True, null=True, verbose_name="消耗时间"),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="product_code",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="产品编码"
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["order_date", "consumption_time"],
                name="data_entry__order_d_2c4d26_idx",
            ),
        ),
    ]
