# Generated by Django 4.2.7 on 2026-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0014_alter_materialconsumption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialconsumption",
            name="product_code",
            field=models.CharField(max_length=100, verbose_name="产品编码"),
        ),
    ]
