# Generated by Django 4.2.7 on 2026-06-23 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0015_alter_materialconsumption_product_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("done", "完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_rows", models.IntegerField(default=0, verbose_name="总行数")),
                (
                    "processed_rows",
                    models.IntegerField(default=0, verbose_name="已处理行数"),
                ),
                ("success_count", models.IntegerField(default=0, verbose_name="成功数")),
                ("error_details", models.JSONField(default=list, verbose_name="错误详情")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "导入任务",
                "verbose_name_plural": "导入任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="consumerdata",
            name="restaurant",
            field=models.CharField(default="", max_length=50, verbose_name="餐厅"),
        ),
        migrations.AlterField(
            model_name="materialconsumption",
            name="restaurant",
            field=models.CharField(default="", max_length=50, verbose_name="餐厅"),
        ),
    ]
