# Generated by Django 4.2.7 on 2026-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0016_importtask_alter_consumerdata_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importtask",
            name="error_file",
            field=models.CharField(blank=True, max_length=500, verbose_name="错误文件路径"),
        ),
    ]
