# Generated by Django 4.2.7 on 2026-09-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0017_importtask_error_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialconsumption",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="consumerdata",
            name="order_date",
            field=models.DateField(null=True, verbose_name="进店日期"),
        ),
    ]
